const vibeRecipes = window.EDU_VIBE_RECIPES || [];
const grid = document.querySelector('#vibe-grid');
const cats = document.querySelector('#vibe-cats');
const search = document.querySelector('#vibe-search');
const count = document.querySelector('#vibe-count');
const selectedRecipe = document.querySelector('#selected-recipe');
let activeCat = 'すべて'; let activeRecipe = null;
const categories = ['すべて', ...new Set(vibeRecipes.map(r => r.cat))];
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderCats(){cats.innerHTML=categories.map(c=>`<button type="button" class="vibe-cat ${c===activeCat?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');}
function renderRecipes(){const q=(search.value||'').trim().toLowerCase();const list=vibeRecipes.filter(r=>(activeCat==='すべて'||r.cat===activeCat)&&(!q||[r.title,r.desc,r.cat,r.logic,r.style,r.asset].join(' ').toLowerCase().includes(q)));count.textContent=`${list.length} RECIPE${list.length===1?'':'S'}`;grid.innerHTML=list.map(r=>`<article class="vibe-card"><div class="vibe-card-top"><span>${esc(r.cat)}</span><small>${esc(r.id)}</small></div><h3>${esc(r.title)}</h3><p>${esc(r.desc)}</p><dl><div><dt>LOGIC</dt><dd>${esc(r.logic)}</dd></div><div><dt>STYLE</dt><dd>${esc(r.style)}</dd></div><div><dt>SOUND</dt><dd>${esc(r.sound)}</dd></div><div><dt>ASSET</dt><dd>${esc(r.asset)}</dd></div></dl><button type="button" class="recipe-use" data-use="${esc(r.id)}">このレシピで依頼文</button></article>`).join('')||'<p>該当するレシピがありません。</p>';}
renderCats();renderRecipes();
cats.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;activeCat=b.dataset.cat;renderCats();renderRecipes();});search.addEventListener('input',renderRecipes);
grid.addEventListener('click',e=>{const b=e.target.closest('[data-use]');if(!b)return;activeRecipe=vibeRecipes.find(r=>r.id===b.dataset.use);selectedRecipe.value=activeRecipe?activeRecipe.title:'';document.querySelector('#ai').scrollIntoView({behavior:'smooth'});});
const form=document.querySelector('#prompt-builder'),output=document.querySelector('#prompt-output'),result=document.querySelector('#prompt-result'),toast=document.querySelector('#toast');
const showToast=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};
form.addEventListener('submit',e=>{e.preventDefault();const subject=document.querySelector('#subject').value.trim()||'小学校向け';const purpose=document.querySelector('#purpose').value.trim()||'Web教材';const notes=document.querySelector('#notes').value.trim();const features=[...form.querySelectorAll('[name="feature"]:checked')].map(x=>x.value);const recipe=activeRecipe?`\n【UIレシピ】${activeRecipe.title}\n【画面方針】${activeRecipe.prompt}\n【推奨LOGIC】${activeRecipe.logic}\n【推奨STYLE】${activeRecipe.style}\n【推奨SOUND】${activeRecipe.sound}\n【推奨ASSET】${activeRecipe.asset}`:'';output.value=`次の小学校向けWeb教材を作成・改善してください。\n\n【教材】${subject}「${purpose}」${recipe}\n【追加要素】${features.length?features.join('、'):'学習目標に必要なものだけ'}${notes?`\n【補足】${notes}`:''}\n\n制作前に EDU KIT を起点として確認してください。\nhttps://github.com/TT-sensei/edu-kit\n\n必ず AI-GUIDE.md に従い、edu-components / edu-effects / sounds-recipe- / edu-assets から必要な資産だけを選んでください。READMEだけで判断せず、実装と公開カタログでAPI・イベント名・CSSクラス・音ID・画像URLが実在することを確認してください。存在しないものを推測で作らないでください。\n\n学習活動への入口と問題画面を最優先にしてください。バッジ、ガチャ、コレクション等は補助要素です。HTML / CSS / Vanilla JavaScriptのみ、npm・ビルド・APIキー・外部DBなし。タブレット横向き・タッチ操作に対応し、長押しを必須にしないでください。`;result.hidden=false;output.focus();});
document.querySelector('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output.value)}catch{output.select();document.execCommand('copy')}showToast('依頼文をコピーしました')});